server {
    listen 18828;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Predict API reverse proxy
    location /api/ {
        proxy_pass http://${PREDICT_API_UPSTREAM}/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
